name: GitHub Actions Demo
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - run: echo "ğŸ‰ The job was automatically triggered by a ${{ github.event_name }} event."
      - name: Build the application
        run: |
          npm install
      - name: Deploy the application on github pages
        run: |
          npm run deploy        
      - run: echo "ğŸ This job's status is ${{ job.status }}."
